on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

name: Slim WASM
jobs:
  wasm:
    name: wasm (${{matrix.architecture}})
    runs-on: ubuntu-24.04
    container:
      image: emscripten/emsdk:4.0.7

    strategy:
      fail-fast: false
      matrix:
        architecture: [ x86 ]
        quantum: [ Q8 ]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Clone ImageMagick libraries
        run: ./checkout.sh --no-configure --dependencies-artifact wasm-${{matrix.architecture}}-static.zip
        working-directory: src/ImageMagick

      - name: Install build tools
        run: ./install.build-tools.sh
        working-directory: build/wasm-${{matrix.architecture}}

      - name: Build ImageMagick
        run: ../../../build/shared/build.imagemagick.sh wasm ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/ImageMagick/ImageMagick

      - name: Build Native
        run: ../../build/shared/build.native.sh wasm ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/Magick.Native

      - name: Create wasm files
        run: npm install && npm run publish
        working-directory: src/wasm-file-creator

      - name: Copy Native
        run: ../../build/wasm-x86/copy.native.sh ../../artifacts wasm ${{matrix.architecture}}
        working-directory: src/Magick.Native

      - name: Upload library
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: wasm-${{matrix.quantum}}-${{matrix.architecture}}
          path: artifacts
